name: Branch Sync

on:
  workflow_call:
    inputs:
      source:
        description: "Branch origin"
        required: true
        type: string
      target:
        description: "Branch destination"
        required: true
        type: string

permissions:
  contents: write

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        env:
          SOURCE: ${{ inputs.source }}
          TARGET: ${{ inputs.target }}
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Update target branch with source branch
        run: |
          git fetch origin "${SOURCE}"
          git checkout "${TARGET}" || git checkout -b "${TARGET}"

          echo "üîÑ Merging '${SOURCE}' into '${TARGET}'..."
          git merge "$SOURCE" --no-edit -X theirs
          echo "‚¨ÜÔ∏è Pushing changes..."
          git push origin "${TARGET}"
